# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: OS versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: 
      matrix:
        [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      fail-fast: false
      python-version: "3.14"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[dev]
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
